src/Entity/OrderInterface.php
<?php

namespace App\Entity;


use Doctrine\Common\Collections\Collection;


interface OrderInterface
{
    const ORDER_RECEIVED = "ORDER_RECEIVED";
    const ORDER_PROCESSING = "ORDER_PROCESSING";
    const ORDER_READY_TO_SHIP = "ORDER_READY_TO_SHIP";
    const ORDER_SHIPPED = "ORDER_SHIPPED";
    const ORDER_CANCELLED = "ORDER_CANCELLED";

    public function getId(): ?int;

    public function getTotal(): ?float;

    public function setTotal(?float $total): \App\Entity\Order;

    public function getDiscount(): ?float;

    public function setDiscount(?float $discount): \App\Entity\Order;

    public function getState(): ?string;

    public function setState(?string $state): \App\Entity\Order;

    public function getCustomer(): ?User;

    public function setCustomer(?User $customer): \App\Entity\Order;

    /**
     * @return Collection|Product[]
     */
    public function getProduct(): Collection;

    public function addProduct(Product $product): \App\Entity\Order;

    public function removeProduct(Product $product): \App\Entity\Order;

    /**
     * @return Collection|ShippingDetails[]
     */
    public function getShipping(): Collection;

    public function addShipping(ShippingDetails $shipping): \App\Entity\Order;

    public function removeShipping(ShippingDetails $shipping): \App\Entity\Order;
}

src/Controller/DepartmentController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class DepartmentController extends AbstractController
{
    /**
     * @Route("/department", name="department")
     */
    public function index(): Response
    {
        return $this->render('department/index.html.twig', [
            'controller_name' => 'DepartmentController',
        ]);
    }



    public function shippingDepartment()
    {
        return $this->render('department/shippingDepartment.html.twig',[
            "department_name" => "Shipping Department"
        ]);
    }

    public function managementDepartment()
    {
        return $this->render('department/managementDepartment.html.twig',[
            "department_name" => "Management Department"
        ]);
    }
}

templates/department/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello DepartmentController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/Users/Nana Asiamah/Documents/Na Proj/PHP/Symfony/Order-System-/src/Controller/DepartmentController.php'|file_link(0) }}">src/Controller/DepartmentController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/Users/Nana Asiamah/Documents/Na Proj/PHP/Symfony/Order-System-/templates/department/index.html.twig'|file_link(0) }}">templates/department/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/department/managementDepartment.html.twig
{% extends 'layout/layout.html.twig' %}

{% block main_content %}
    <div class="card">
        <div class="card-header">
            <h3>All Orders</h3>
        </div>

        <div class="card-body">
            <div class="row">
                <div class="col-12">
                    <div class="table-responsive">
                        <table class="table table-hover">
                            <thead>
                            <tr>
                                <th class="text-center">Order Number</th>
                                <th class="text-center">State</th>
                                <th class="text-center">Date</th>
                                <th class="text-center">Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for order in orders %}
                                <tr>
                                    <td class="text-center">#{{ order.id }}</td>
                                    <td class="text-center">
                                        <span class="badge badge-warning">{{ order.state }}</span>
                                    </td>
                                    <td class="text-center">{{ order.createdAt|date('d/m/Y') }}</td>
                                    <td class="text-center">
                                        <div class="text-center">
                                            <a href="{{ path('order_logs',{'id': order.id}) }}" type="button" class="btn btn-info btn-lg" data-bs-toggle="modal"
                                               data-bs-target="#orderLogsModal"><i
                                                        class="mdi mdi-eye"></i></a>
                                        </div>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                        <div class="navigation">
                            {{ knp_pagination_render(orders) }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}


{% block title %}
    {{ department_name }}
{% endblock %}

{% block javascripts %}
    <script>
        // $(`.order-departments`).addClass('active');
        // $(`.department-expand`).addClass('show');
    </script>
{% endblock %}

templates/department/pickingDepartment.html.twig
{% extends 'layout/layout.html.twig' %}

{% block main_content %}
    <div class="card">
        <div class="card-header">
            <h3>Received Orders</h3>
        </div>

        <div class="card-body">
            <div class="row">
                <div class="col-12">
                    <div class="table-responsive">
                        <table class="table table-hover">
                            <thead>
                            <tr>
                                <th class="text-center">Order Number</th>
                                <th class="text-center">State</th>
                                <th class="text-center">Date</th>
                                <th class="text-center">Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for order in orders %}
                            <tr>
                                <td class="text-center">#{{ order.id }}</td>
                                <td class="text-center">
                                    <span class="badge badge-warning">{{ order.state }}</span>
                                </td>
                                <td class="text-center">{{ order.createdAt|date('d/m/Y') }}</td>
                                <td class="text-center">
                                    <div class="text-center">
                                        <a href="{{ path('show_order',{'id': order.id}) }}" type="button" class="btn btn-info btn-lg" data-bs-toggle="modal"
                                                data-bs-target="#orderLogsModal"><i
                                                    class="mdi mdi-eye"></i></a>
                                    </div>
                                </td>
                            </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                        <div class="navigation">
                            {{ knp_pagination_render(orders) }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}


{% block title %}
    {{ department_name }}
{% endblock %}

{% block javascripts %}
    <script>
        // $(`.order-departments`).addClass('active');
        // $(`.department-expand`).addClass('show');
    </script>
{% endblock %}

templates/department/shippingDepartment.html.twig
{% extends 'layout/layout.html.twig' %}

{% block title %}
    {{ department_name }}
{% endblock %}

{% block main_content %}
    <div class="card">
        <div class="card-header">
            <h3>Ready To Be Shipped</h3>
        </div>

        <div class="card-body">
            <div class="row">
                <div class="col-12">
                    <div class="table-responsive">
                        <table class="table table-hover">
                            <thead>
                            <tr>
                                <th class="text-center">Order Number</th>
                                <th class="text-center">State</th>
                                <th class="text-center">Box ID</th>
                                <th class="text-center">Date</th>
                                <th class="text-center">Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for order in orders %}
                                <tr>
                                    <td class="text-center">#{{ order.id }}</td>
                                    <td class="text-center">
                                        <span class="badge badge-warning">{{ order.state }}</span>
                                    </td>
                                    <td class="text-center">{{ order.boxId }}</td>
                                    <td class="text-center">{{ order.createdAt|date("d/m/Y") }}</td>
                                    <td class="text-center">
                                        <div class="text-center">
                                            <a href="{{ path('show_order',{'id': order.id}) }}"
                                               class="btn btn-info btn-lg"><i
                                                        class="mdi mdi-eye"></i></a>
                                        </div>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                        <div class="navigation">
                            {{ knp_pagination_render(orders) }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}


{% block javascripts %}
    {{ parent() }}
    <script>

    </script>
{% endblock %}

templates/department/viewLogs.twig
{% extends 'layout/layout.html.twig' %}



{% block title %}
    Order #{{ order.id }}
{% endblock %}

{% block stylesheets %}
    {{ parent() }}
{% endblock %}

{% block javascripts %}
    {{ parent() }}

    <script type="module">
        $(document).ready(function () {


            /*Mark Order*/
            $(document).on('click', '#markOrder', function () {
                let orderDetails = {{ order.id }};

                JsLoadingOverlay.show({
                    'spinnerIcon': 'ball-circus',
                    'spinnerColor': '#ffffff',

                });

                $.ajax({
                    url: `/order/${orderDetails}/processing`,
                    type: 'PUT',
                    contentType: 'application/json',
                    data: orderDetails
                }).then((data) => {
                    console.log(data)
                    $('#markOrder').addClass('disabled');
                    $('#productBoxID').removeClass('disabled');
                    JsLoadingOverlay.hide()
                }).catch((err) => {
                    console.log(err)
                });
            });
        });


    </script>
{% endblock %}

{% block main_content %}

    <div class="card">
        <div class="card-header">
            <h3>Order #{{ order.id }}</h3>
        </div>


        <div class="card-body ">
            <div class="row">
                <div class="col-md-6">
                    <div class="card">
                        <div class="card-header">
                            <h5>Products</h5>
                        </div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-12 h-100">
                                    <div class="bg-primary p-4 rounded">
                                        <div id="profile-list-left">
                                            {% for product in order.product %}
                                                <div class="card rounded mb-2">
                                                    <div class="card-body p-3">
                                                        <div class="media">
                                                            <div class="media-body">
                                                                <h6 class="mb-1">{{ product.name }}</h6>
                                                                <p class="mb-0 text-muted">
                                                                    Amount : {{ product.amount }}
                                                                </p>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            {% endfor %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="card">
                        <div class="card-header">
                            <div class="card-title">
                                Shipping Details
                            </div>
                        </div>

                        <div class="card-body">
                            <div class="card">
                                <div class="card-body">
                                    <ul class="bullet-line-list">
                                        <li>
                                            <h6>Shipping Method</h6>
                                            <p>{{ order.shipping.first.method }}</p>
                                        </li>
                                        <li>
                                            <h6>Shipping Address</h6>
                                            <p>{{ order.shipping.first.address }}</p>
                                        </li>
                                        <li>
                                            <h6>Phone Number</h6>
                                            <p>{{ order.shipping.first.phoneNumber }}</p>
                                        </li>

                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div>
                <div class="row">
                    {% if order.state is same as("ORDER_RECEIVED") or order.state is same as ("ORDER_PROCESSING" )%}
                    <div class="col-md-6">
                        <div class="form-group">
                            <button class="btn btn-primary btn-icon-text" id="markOrder" style="color: white">
                                <i class="ti-reload btn-icon-prepend"></i>
                                Mark Picking Products
                            </button>
                            <button class="btn btn-danger disabled btn-icon-text" id="productBoxID" style="color: white"
                                    data-bs-toggle="modal"
                                    data-bs-target="#orderLogsModal">
                                <i class="ti-upload btn-icon-prepend"></i>
                                Add Product Box ID
                            </button>
                        </div>
                    </div>
                    {% endif %}

                    {% if order.state is same as ("ORDER_READY_TO_SHIP")%}
                    <div class="col-md-6">
                        <div class="form-group">
                            <button class="btn btn-danger  btn-icon-text" id="productBoxID" style="color: white"
                                    data-bs-toggle="modal"
                                    data-bs-target="#shippingMethodModal">
                                <i class="fas fa-ship btn-icon-prepend"></i>
                                Enter Shipping Method
                            </button>
                        </div>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>


    </div>






{% endblock %}

templates/department/viewOrder.html.twig
{% extends 'layout/layout.html.twig' %}



{% block title %}
    Order #{{ order.id }}
{% endblock %}

{% block stylesheets %}
    {{ parent() }}
{% endblock %}

{% block javascripts %}
    {{ parent() }}

    <script type="module">
        $(document).ready(function () {


            /*Mark Order*/
            $(document).on('click', '#markOrder', function () {
                let orderDetails = {{ order.id }};

                JsLoadingOverlay.show({
                    'spinnerIcon': 'ball-circus',
                    'spinnerColor': '#ffffff',

                });

                $.ajax({
                    url: `/order/${orderDetails}/processing`,
                    type: 'PUT',
                    contentType: 'application/json',
                    data: orderDetails
                }).then((data) => {
                    console.log(data)
                    $('#markOrder').addClass('disabled');
                    $('#productBoxID').removeClass('disabled');
                    JsLoadingOverlay.hide()
                }).catch((err) => {
                    console.log(err)
                });
            });
        });


    </script>
{% endblock %}

{% block main_content %}

<div class="card">
    <div class="card-header">
        <h3>Order #{{ order.id }}</h3>
    </div>


    <div class="card-body flex-row ">
        <div class="row">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header">
                        <h5>Products</h5>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-12 h-100">
                                <div class="bg-primary p-4 rounded">
                                    <div id="profile-list-left">
                                        {% for product in order.product %}
                                            <div class="card rounded mb-2">
                                                <div class="card-body p-3">
                                                    <div class="media">
                                                        <div class="media-body">
                                                            <h6 class="mb-1">{{ product.name }}</h6>
                                                            <p class="mb-0 text-muted">
                                                                Amount : {{ product.amount }}
                                                            </p>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header">
                        <div class="card-title">
                            Shipping Details
                        </div>
                    </div>

                    <div class="card-body">
                        <div class="card">
                            <div class="card-body">
                                <ul class="bullet-line-list">
                                    <li>
                                        <h6>Shipping Method</h6>
                                        <p>{{ order.shipping.first.method }}</p>
                                    </li>
                                    <li>
                                        <h6>Shipping Address</h6>
                                        <p>{{ order.shipping.first.address }}</p>
                                    </li>
                                    <li>
                                        <h6>Phone Number</h6>
                                        <p>{{ order.shipping.first.phoneNumber }}</p>
                                    </li>

                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% if order.isIssue is same as (true) %}
                <div class="col-md-6">
                    <div class="card">
                        <div class="card-header">
                            <div class="card-title">
                                Errors
                            </div>
                        </div>

                        <div class="card-body">
                            <div class="card">
                                <div class="card-body">
                                    <ul class="bullet-line-list">
                                        <li>
                                            <h6>Issue</h6>
                                            <p class="text-danger">{{ issue.orderIssue }}</p>
                                        </li>
                                        <li>
                                            <h6>Problem</h6>
                                            <p class="text-danger">{{ issue.description }}</p>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endif %}
        </div>

        <div>
            <div class="row">
                {% if order.state is same as("ORDER_RECEIVED") or order.state is same as ("ORDER_PROCESSING" ) %}
                    <div class="col-md-6">
                        <div class="form-group">
                            <button class="btn btn-primary btn-icon-text" id="markOrder" style="color: white">
                                <i class="ti-reload btn-icon-prepend"></i>
                                Mark Picking Products
                            </button>
                            <button class="btn btn-success disabled btn-icon-text" id="productBoxID"
                                    style="color: white"
                                    data-bs-toggle="modal"
                                    data-bs-target="#orderLogsModal">
                                <i class="ti-upload btn-icon-prepend"></i>
                                Add Product Box ID
                            </button>
                        </div>
                        <div class="col-md-6">
                            <form action="{{ path('cancel_order',{"id":order.id}) }}" method="post">
                                <input type="hidden" name="_csrf_token"
                                       value="{{ csrf_token('cancel_order') }}"
                                >
                                <button class="btn btn-danger btn-icon-text" type="submit" style="color: white">
                                    <i class="ti-trash btn-icon-prepend"></i>
                                    Cancel Order
                                </button>
                            </form>
                        </div>


                    </div>
                {% endif %}


            </div>
            <div class="row">
                {% if order.state is same as ("ORDER_READY_TO_SHIP") %}
                    <div class="col-md-6">
                        <div class="form-group">
                            <button class="btn btn-danger  btn-icon-text" id="productBoxID" style="color: white"
                                    data-bs-toggle="modal"
                                    data-bs-target="#shippingMethodModal">
                                <i class="fas fa-ship btn-icon-prepend"></i>
                                Enter Shipping Method
                            </button>
                            <button class="btn btn-info  btn-icon-text" id="reportIssue" style="color: white"
                                    data-bs-toggle="modal"
                                    data-bs-target="#reportIssueModal">
                                <i class="ti-info btn-icon-prepend"></i>
                                Report Issue
                            </button>
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>


    </div>

    {# Box Id  Modal #}
    <div class="modal fade" id="orderLogsModal" tabindex="-1" role="dialog" aria-labelledby="orderLogsModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel"><i class="mdi menu-icon mdi-history"></i> Shipping
                        Details</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    {{ form_start(form) }}
                    {{ form_row(form.boxId) }}
                    <button type="submit" class="form-control btn btn-primary">Submit</button>
                    {{ form_end(form) }}
                </div>
            </div>
        </div>
    </div>
    {# End Of Modal #}


    {# Box Id  Modal #}
    <div class="modal fade" id="reportIssueModal" tabindex="-1" role="dialog" aria-labelledby="reportIssueModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel"><i class="mdi menu-icon mdi-information-outline"></i>
                        Report Issue</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    {{ form_start(issueForm) }}
                    {{ form_row(issueForm.orderIssue) }}
                    {{ form_row(issueForm.description) }}
                    <div class="form-group">
                        <button type="submit" class="form-control btn btn-primary">Submit</button>
                    </div>
                    {{ form_end(issueForm) }}
                </div>
            </div>
        </div>
    </div>
    {# End Of Modal #}



    {# Box Id  Modal #}
    <div class="modal fade" id="shippingMethodModal" tabindex="-1" role="dialog"
         aria-labelledby="shippingMethodModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel"><i class="mdi menu-icon mdi-history"></i> Shipping
                        Details</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    {{ form_start(shippingMethodForm) }}
                    {{ form_row(shippingMethodForm.shippingCompany) }}
                    {{ form_row(shippingMethodForm.trackingNumber) }}
                    {{ form_row(shippingMethodForm.documentPath) }}
                    <button type="submit" class="form-control btn btn-primary">Submit</button>
                    {{ form_end(shippingMethodForm) }}
                </div>
            </div>
        </div>
    </div>
    {# End Of Modal #}


    {% endblock %}